### PR TITLE
fix use of global variables

### PR DESCRIPTION
**Pull request by KristofferC**
global variables bad for performance etc

Fixes:

```jl
julia> @code_warntype foo()
Variables:
  d::DualNumbers.Dual{Float64}
  a::Any

Body:
  begin  # none, line 2:
      a = 0.0 # none, line 3:
      d = $(Expr(:new, DualNumbers.Dual{Float64}, 1.0, 1.0)) # none, line 5:
      a = a::Float64 + (Main.dualpart)(d::DualNumbers.Dual{Float64})::Any::Any # none, line 6:
      return a
  end::Any
```

### CODE REVIEW

**Comment by mlubin** [comment]
Thanks!

**Comment by KristofferC** [comment]
Maybe should tag a new version since `realpart` is used in Optim for example.

**Comment by KristofferC** [comment]
I could do it... with permission.

**Comment by mlubin** [comment]
Granted

**Pull request merged**
