### PR TITLE
add constant number with zero real and unitary du

### PR DESCRIPTION
**Pull request by gasagna**
This is a useful addition which was missing, taken directly from complex.jl in Base.

### CODE REVIEW

**Comment by mlubin** [comment]
Seems like a good idea. The package isn't very consistent in using ``du`` or ``epsilon`` or ``ϵ``. Given that named constants can't currently be deprecated (as far as I know), should we try to flesh out the name more? I'm okay with ``du`` but maybe others will have a different opinion, @scidom @johnmyleswhite @timholy.
(Also, you should add a line ``export du`` to the PR).

**Comment by mlubin** [comment]
Adding some uses of ``du`` in the tests would be helpful as well.

**Comment by timholy** [comment]
It seems we need one constant and one function, which can't share the same name. I don't have strong feelings about what gets chosen, but I do think the constant should match what's printed (so `du` seems to have a lot going for it).

**Comment by gasagna** [comment]
I think a much better name for the constant  would be  \epsilon (the symbol). It is short, and neat, especially when printed out in the repl.  We can still have the function named ``epsilon``, which I think it is clearer.

I have also added few tests and an export for the constant to this pull request. Changing ``du`` to something else can be done at a later stage.

**Comment by mlubin** [comment]
Could you squash the commits? Looks good to merge after that.

**Comment by gasagna** [comment]
Can I do that online from github.com?

**Comment by scidom** [comment]
@gasagna usually the pain-free method is to simply create a new PR consisting of a single commit.

**Comment by gasagna** [comment]
Ok, so I will close this pull request and create a new one. Thanks.

**Pull request closed without merging**
