### PR TITLE
Fix depwarn on 0.6 due to vectorized functions

### PR DESCRIPTION
**Pull request by yuyichao**
Also use tuple type instead of tuples (Ref https://github.com/JuliaLang/julia/pull/18444 and it's easier to infer in general)

### CODE REVIEW

**Comment by mlubin** [comment]
Could you also update travis here? Thanks!

**Comment by yuyichao** [comment]
And done.

**Comment by tkelman** [comment]
Note that this caused `value` to start being exported which caused EmpiricalRisks.jl's tests to start failing - http://pkg.julialang.org/logs/EmpiricalRisks_0.4.log

**Comment by mlubin** [comment]
That's unfortunate, ``value`` should not be exported. I'll accept PRs to fix.

**Pull request merged**
